<?php

use Illuminate\Database\Migrations\Migration;

// NOTE: This migration was originally generated by spatie/laravel-permission.
// The package has been removed from the project. This migration is now a no-op
// to maintain migration history integrity. The Spatie tables are dropped by
// migration 2026_04_01_032540_drop_spatie_permission_tables.
return new class extends Migration
{
    public function up(): void
    {
        // No-op — Spatie Permission package removed from project
    }

    public function down(): void
    {
        // No-op
    }
};
